services:
  - type: web
    name: license-plate-detection
    env: python
    startCommand: gunicorn app:app
    buildCommand: |
      echo "Python version:" $(python --version)
      pip install --upgrade pip
      pip install -r requirements.txt

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6

    autoDeploy: true